package com.siui.sysapp.applock.data.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.siui.sysapp.applock.data.entity.InstallAppInfo;
import com.siui.sysapp.applock.data.entity.LockAppInfo;

import com.siui.sysapp.applock.data.model.InstallAppInfoDao;
import com.siui.sysapp.applock.data.model.LockAppInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig installAppInfoDaoConfig;
    private final DaoConfig lockAppInfoDaoConfig;

    private final InstallAppInfoDao installAppInfoDao;
    private final LockAppInfoDao lockAppInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        installAppInfoDaoConfig = daoConfigMap.get(InstallAppInfoDao.class).clone();
        installAppInfoDaoConfig.initIdentityScope(type);

        lockAppInfoDaoConfig = daoConfigMap.get(LockAppInfoDao.class).clone();
        lockAppInfoDaoConfig.initIdentityScope(type);

        installAppInfoDao = new InstallAppInfoDao(installAppInfoDaoConfig, this);
        lockAppInfoDao = new LockAppInfoDao(lockAppInfoDaoConfig, this);

        registerDao(InstallAppInfo.class, installAppInfoDao);
        registerDao(LockAppInfo.class, lockAppInfoDao);
    }
    
    public void clear() {
        installAppInfoDaoConfig.clearIdentityScope();
        lockAppInfoDaoConfig.clearIdentityScope();
    }

    public InstallAppInfoDao getInstallAppInfoDao() {
        return installAppInfoDao;
    }

    public LockAppInfoDao getLockAppInfoDao() {
        return lockAppInfoDao;
    }

}
